### ISSUE TITLE
DeltaGeneratorTool has been compiled by a more recent version of the Java Runtime

### ISSUE THREAD

**Issue by fransanlag** [IHTSDO/delta-generator-tool#3]
Hi,

I've just installed the newest version of Java and when I try to execute DeltaGeneratorTool I get the following error.

Any help would be most appreciated.

Regards,

C:\Prueba delta>java -jar DeltaGeneratorTool.jar 20210731 SnomedCT_InternationalRF2_PRODUCTION_20220228T120000Z.zip
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/snomed/otf/delta/DeltaGeneratorTool has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)

**Comment by pgwilliams** [comment]
Hi @fransanlag it looks like, while you might have _installed_ the newest version of java, that's not what's on your PATH.   Try typing:
`java --version`
on the command line to see what you actually get when you execute java.   This resource might help you figure out why that is:  https://superuser.com/questions/479889/wrong-java-version-being-reported

Class file version 52 is equivalent to Java 8 and we've compiled against 55 which is Java 11.   Here's a list of major version numbers:  https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by fransanlag** [comment]
Thank you so much, Peter... I managed to solve it.
Regards,
